### ISSUE TITLE
hmedians not found

### ISSUE THREAD

**Issue by alexgleith** [frontiersi/odc-sandbox-notebooks#5]
In the notebook `dcal/DCAL_Land_Change.ipynb` in step 20 I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-9740b870cefe> in <module>()
----> 1 from utils.data_cube_utilities.dc_mosaic import ls8_unpack_qa, ls7_unpack_qa
      2 
      3 unpack_function = {"LANDSAT_7": ls7_unpack_qa,
      4                    "LANDSAT_8": ls8_unpack_qa}
      5 

~/examples/dcal/utils/data_cube_utilities/dc_mosaic.py in <module>()
     28 import collections
     29 from collections import OrderedDict
---> 30 import hdmedians as hd
     31 
     32 import datacube

ModuleNotFoundError: No module named 'hdmedians'
```

**Comment by alexgleith** [comment]
Hey @LSgeo can you check this out? I guess all the notebooks will need to be run now that they're in the Sandbox.

**Comment by alexgleith** [comment]
Same issue in `dcal/DCAL_Cloud_Statistics.ipynb`

**Comment by LSgeo** [comment]
Hey Alex, the issue is a required package. I mentioned it to @felipk101 at one point, and he said he would look into installing the required packages globally:
The ones required are:

hdmedians rasterstats seaborn sklearn

**Comment by alexgleith** [comment]
Aha, got it. I do remember him asking me to do this some time ago. I'll add them to the docker image now.

**Comment by alexgleith** [comment]
Ok, I think that's fixed it. Can you check and confirm please, @LSgeo?

**Comment by LSgeo** [comment]
Matt reported the issue seems fixed in his Sandbox issue. I think we can close the issue.

**Comment by alexgleith** [comment]
Hey @chriscmorgan this is an issue again. Can you please check out if it's still being installed?
